"use client";

import { useQuery } from "@tanstack/react-query";

import { Header } from "@/components/header";
import { Subtext } from "@/components/subtext";

import { getTermsQueryOptions } from "@/services/info/queries";

import { getFormattedDateTime } from "@/utils/date";

import { TermsAccordion } from "./terms-accordion";

function TermsPage() {
  const { data } = useQuery(getTermsQueryOptions());
  const terms = data?.termsAndConditions;

  if (!terms) {
    return <h2>Terms not found</h2>;
  }

  const formattedDate = getFormattedDateTime(terms.lastUpdated);
  return (
    <div className="my-10 space-y-6">
      <div className="flex justify-between">
        <Header>Terms of service</Header>
        <Subtext>Last updated: {formattedDate}</Subtext>
      </div>
      <h3 className="my-2 text-lg">{terms.introduction}</h3>
      <TermsAccordion termsConent={terms.sections} />
      <div className="flex justify-between">
        <h3 className="my-2 text-lg">{terms.acknowledgement}</h3>
        <Subtext className="text-right">
          Terms and conditions were generated by ChatGPT.
        </Subtext>
      </div>
    </div>
  );
}

export { TermsPage };
