import { parseAbsoluteToLocal } from '@internationalized/date';

import { Header, Subtext } from '@repo/shared/components';
import { getFormattedDateTime } from '@repo/shared/utils/formatters/date-formatter/index';

import { getTermsOfService } from '@/actions/get-terms-of-service';

import { TermsAccordion } from './terms-accordion';

export default async function TermsPage() {
  const data = await getTermsOfService();
  const terms = data.termsAndConditions;
  const formattedDate = getFormattedDateTime(
    parseAbsoluteToLocal(terms.updatedAt),
  );

  return (
    <div className="space-y-6">
      <div className="flex justify-between">
        <Header>Terms of service</Header>
        <Subtext>Last updated: {formattedDate}</Subtext>
      </div>
      <h3 className="my-2 text-lg">{terms.introduction}</h3>
      <TermsAccordion termsConent={terms.sections} />
      <div className="flex justify-between">
        <h3 className="my-2 text-lg">{terms.acknowledgement}</h3>
        <Subtext className="text-right">
          Terms and conditions were generated by ChatGPT.
        </Subtext>
      </div>
    </div>
  );
}
