name: build
on: [push]
jobs:
  prettier:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Run  Build
        run: pnpm build
