name: eslint
on: [push]
jobs:
  prettier:
    name: Run Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Run Eslint
        run: bun run lint
