name: prettier
on: [push]
jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Run Prettier
        run: bun run prettier-check
